const LOG_SERVICES = {
    DB: {
        DATABASE: 'DATABASE',
        CONNECT_SUCCESS: 'CONNECT DATABASE SUCCESS',
        CONNECT_FAILED: 'CONNECT DATABASE FAILED',
        CMD: {
            FIND_USER: 'FIND_USER',
            CREATE_USER: 'CREATE_USER',
            UPDATE_USER: 'UPDATE_USER',
            CHECK_USER_STATUS: 'CHECK_USER_STATUS',
            SYSTEM: 'SYSTEM',
            FIND_USER_INFO: 'FIND_USER_INFO',
            CREATE_USER_INFO: 'CREATE_USER_INFO',
            UPDATE_USER_INFO: 'UPDATE_USER_INFO',
        },
        STATUS: {
            SUCCESS: 'SUCCESS',
            FAILED: 'FAILED',
        },
        MESSAGE: {
            NOT_FOUND: 'NOT_FOUND',
            SUCCESS: 'SUCCESS',
            NOT_VERIFY: 'NOT_VERIFY',
            CONFLICT: 'CONFLICT',
        },
    },
    MESSAGE_INCOMMING: 'INCOMMING',
    MESSAGE_OUTGOING: 'OUTGOING:',
    OUTGOING_STATUS: {
        SUCCESS: 'SUCCESS',
        CREATED: 'CREATED',
        SYSTEM_ERROR: 'SYSTEM_ERROR',
        CONFLICT: 'CONFLICT',
        NOT_FOUND: 'NOT_FOUND',
        WRONG_PASSWORD: 'WRONG_PASSWORD',
        UNAUTHORIZED: 'UNAUTHORIZED',
        MISSING_OR_INVALID: 'MISSING_OR_INVALID',
        EMAIL_NOT_VERIFY: 'EMAIL_NOT_VERIFY',
    },
};

export default Object.freeze(LOG_SERVICES);
